/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reaction.java
 *
 * Created on 01-Dec-2010, 23:10:59
 */



/**
 *
 * @author mhh
 */
public class ILTMethod extends javax.swing.JFrame {

    /** Creates new form Reaction */
    public ILTMethod() {

        initComponents();
          //setDefaultCloseOperation(2);
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         setResizable(false);
         setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18));
        jLabel1.setText("MESMER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 0, 184, 39);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18));
        jLabel2.setText("ITL Method");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 30, 130, 23);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Changes");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 300, 70, 17);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 390, 10);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 100, 390, 10);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(-10, 230, 390, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(150, 0, 60, 360);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(170, 10, 190, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(170, 60, 190, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField3);
        jTextField3.setBounds(170, 110, 190, 30);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(0, 150, 390, 10);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Concentration");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(26, 190, 120, 17);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField6);
        jTextField6.setBounds(170, 170, 190, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setText("Excess Reactant");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 170, 120, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\MESMER_GUI_CODE\\MESMER_V2\\src\\mesmer_v2\\ITLS3b.gif")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 110, 80, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITLS1b.gif"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 10, 80, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\MESMER_GUI_CODE\\MESMER_V2\\src\\mesmer_v2\\ITLS2b.gif")); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 60, 80, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(160, 250, 200, 90);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setText("Scientific Rational ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 260, 120, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel11.setText("for ");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 280, 40, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 60, 380, 360);

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(160, 130, 190, 30);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 430, 150, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public String get_ILT_A()
   {
       return jTextField1.getText();
   }

   public String get_ILT_N()
   {
       return jTextField2.getText();
   }

   public String get_ILT_E()
   {
       return jTextField3.getText();
   }

   public String get_ExcessRegionalConcentration()
   {
       return jTextField6.getText() ;
   }

//   public String get_Excess()
//   {
//       return jTextField4.getText() ;
//   }

   public String get_ScienfifiRational()
   {
         return jTextArea1.getText();
   }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ILTMethod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
