/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReactionPan2.java
 *
 * Created on 15-Dec-2010, 12:18:51
 */



import java.awt.Cursor;
import java.awt.event.ActionEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mhh
 */
public class ReactionPan2 extends javax.swing.JPanel {


     /** Creates new form MainGUI */
    String method = "RRKM";
    String reactant ="1";
    String product = "1";
    public JTextField jtestFieldReact2 = new JTextField();
    public JTextField jtextFiledPrduction = new JTextField();
 //   public JComboBox reactantCombo1 = new JComboBox(new String[] {"Deficent", "Excess", "Sink", "Model"} );
    public JComboBox reactantCombo2 = new JComboBox(new String[] {"Deficent", "Excess", "Sink", "Model"} );
   // public JComboBox productCombo1 = new JComboBox(new String[] {"Deficent", "Excess", "Sink", "Model"} );
    public JComboBox productCombo2 = new JComboBox(new String[] {"Deficent", "Excess", "Sink", "Model"} );
    public Reactant1 reactant1Input = new Reactant1();
    public Reactant2 reactant2Input = new Reactant2();
    
    public Product1 product1Input = new Product1();
    public Product2 product2Input = new Product2();
    public String reactionCombo_1Value = "Sink";
    public String reactantCombo_2Value = "Deficent";
    public String productCombo_1Value = "Sink";
    public String productCombo_2Value = "Deficent";
    public TransitionState transitionStateInput = new TransitionState();
    public ILTMethod iltMethodInput = new ILTMethod();

    public boolean rRM_ticked = false;
    /** Creates new form ReactionPan2 */
    public ReactionPan2() {
        initComponents();
    }

    public ReactionPan2(int reactionNumber)
    {
        //Action Listner for reaction 1 Combo box
//         reactantCombo1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed (java.awt.event.ActionEvent evt) {
//                reactantCombo1ActionPerformed(evt);
//            }
//        });
        
         //Action Listner for reaction 2 Combo box
         reactantCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed (java.awt.event.ActionEvent evt) {
                reactantCombo2ActionPerformed(evt);
            }
        });

        //Action Listner from product 1 Combo box
//        productCombo1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt ) {
//              productCombo1ActionPerformed(evt);
//            }
//        });

           //Action Listner from product 2 Combo box
        productCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt ) {
              productCombo2ActionPerformed(evt);
            }
        });

        initComponents();
        //setDefaultCloseOperation ( JFrame.EXIT_ON_CLOSE );
        jLabel6.setText("Reaction " + reactionNumber);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        productCombo1a = new javax.swing.JComboBox();
        reactantCombo1a = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(730, 170));
        setPreferredSize(new java.awt.Dimension(730, 170));
        setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(730, 170));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 170));
        jPanel2.setLayout(null);

        jButton3.setText("Fill Reactant");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(30, 140, 130, 22);

        jButton4.setText("Fill Product");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(220, 140, 146, 22);

        jButton5.setText("Fill Transition State");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(570, 140, 150, 23);

        jButton6.setText("Fill ILT");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(430, 140, 120, 23);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(10, 90, 110, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(220, 90, 110, 20);

        jTextField3.setEditable(false);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(580, 90, 140, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(120, 30, 40, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(330, 30, 50, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Reactant");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 30, 66, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Product");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 30, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Transition State");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(590, 30, 126, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Method");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(460, 30, 100, 20);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(560, 30, 50, 140);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(210, 30, 40, 140);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(420, 30, 50, 140);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(0, 60, 730, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Reaction 1");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, -3, 730, 30);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox1.setText("     RRKM");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(440, 83, 110, 30);

        productCombo1a.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sink", "Model" }));
        productCombo1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCombo1aActionPerformed(evt);
            }
        });
        jPanel2.add(productCombo1a);
        productCombo1a.setBounds(335, 90, 80, 20);

        reactantCombo1a.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sink", "Model" }));
        reactantCombo1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reactantCombo1aActionPerformed(evt);
            }
        });
        jPanel2.add(reactantCombo1a);
        reactantCombo1a.setBounds(125, 90, 80, 20);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 730, 170);
    }// </editor-fold>//GEN-END:initComponents

    public void reactantCombo1ActionPerformed(ActionEvent evt)
    {
        reactionCombo_1Value = (String) reactantCombo1a.getSelectedItem();
        System.out.println("The selection from reaction 1 combo box is " + reactionCombo_1Value ) ;
    }

    public void reactantCombo2ActionPerformed(ActionEvent evt)
    {
        reactantCombo_2Value = (String) reactantCombo2.getSelectedItem();
        System.out.println("The selection from reaction 2 combo box is " + reactantCombo_2Value );
    }

    public void productCombo1ActionPerformed(ActionEvent evt)
    {
        productCombo_1Value = (String) productCombo1a.getSelectedItem();
        System.out.println("The slection from product 1 combo box is " + productCombo_1Value );
    }

     public void productCombo2ActionPerformed(ActionEvent evt)
    {
        productCombo_2Value = (String) productCombo2.getSelectedItem();
        System.out.println("The slection from product 1 combo box is " + productCombo_2Value );
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(reactant.equals("1"))
        {
            displayReactatn1();
            reactant1Input.initialisationValueDisplay(jTextField1.getText());
            reactant1Input.setVisible(true);
        }
           // new Reactant1().setVisible(true);
        else
           // new Reactant2().setVisible(true);
        {
           displayReactatn2();
           reactant2Input.initialisationValueDisplay(jTextField1.getText(), jtestFieldReact2.getText());
           reactant2Input.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(product.equals("1"))
        {
            displayProduct1();
            product1Input.initialisationValueDisplay(jTextField2.getText());
            product1Input.setVisible(true);
        }
        else
        {
            displayProduct2();
            product2Input.initialisationValueDisplay(jTextField2.getText(), jtextFiledPrduction.getText() );
            product2Input.setVisible(true);
        }
}//GEN-LAST:event_jButton4ActionPerformed


    public void displayReactatn1()
    {
        System.out.println("Combo selected " + getNo_ReactantComboSelected() );
        System.out.println("Reactant data is " + getReactant_1TextField());

    }

    public void  displayReactatn2()
    {
        System.out.println(" Combo Reactant selected " + getNo_ReactantComboSelected() );
        System.out.println(" Text filed 1  " + getReactant_1TextField() );
        System.out.println(" Text filed 2  " + getReactant_2TextField() );
        System.out.println(" Selected Combo 1 Reactant " + getReactantCombo1() );
        System.out.println(" Selected combo 2 Reactant  " + getReactantCombo2()  );
    }

    public void displayProduct1()
    {
        System.out.println("Product Combo box selected  " + getNo_ProductComboSelected() );
        System.out.println(" Product data is " + getProduct_1TextField() );

    }

     public void displayProduct2()
     {
        System.out.println(" Combo Product selected " + getNo_ProductComboSelected() );
        System.out.println(" Text filed 1  " + getProduct_1TextField() );
        System.out.println(" Text filed 2  " + getProduct_2TextField() );
        System.out.println(" Selected Combo 1 Product " + getProductCombo1()  );
        System.out.println(" Selected combo 2 Product  " + getProductCombo2() );

     }

    public String getNo_ReactantComboSelected()
    {
        return reactant;
    }

    public String getReactant_1TextField()
    {
        return jTextField1.getText();
    }

    public String getReactant_2TextField()
    {
        return jtestFieldReact2.getText();
    }

    public String getReactantCombo1()
    {
        return reactionCombo_1Value;
    }

    public String getReactantCombo2()
    {
        return reactantCombo_2Value;
    }

    public String getNo_ProductComboSelected()
    {
        return product;
    }

    public String getProduct_1TextField()
    {
        return jTextField2.getText();
    }

    public String getProduct_2TextField()
    {
        return jtextFiledPrduction.getText();
    }

    public String getProductCombo1()
    {
        return productCombo_1Value;
    }

   public String getProductCombo2()
   {
       return productCombo_2Value;
   }

   public String get_TransitionStateValue()
   {
       return jTextField3.getText();
   }

   public boolean get_RRKM()
   {
        return rRM_ticked;
   }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        if(rRM_ticked== true)
        {
            displayTransitionValue();
            transitionStateInput.initialisationValueDisplay(jTextField3.getText());
            transitionStateInput.setVisible(true);
        }
        else
        {
             JOptionPane.showMessageDialog(null,
            "Sorry you have to select RRKM before this can be used",
             "Transition State",
            JOptionPane.ERROR_MESSAGE);
        }

}//GEN-LAST:event_jButton5ActionPerformed


    public void displayTransitionValue()
    {
        System.out.println("The transition state value entered is " + get_TransitionStateValue());
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//        if(method.equals("RRKM")) {
//            // new ILTMethod().setVisible(true);
//            new RRKM_Method().setVisible(true);
//        } else if(method.equals("ILT")) {
//            new ILTMethod().setVisible(true);
//        }

        if(rRM_ticked== false)
        {
            iltMethodInput.setVisible(true);
                  //  new ILTMethod().setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,
            "Sorry you have to deselect RRKM before this can be used",
             "ILT Error",
            JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        reactant = (String) jComboBox1.getSelectedItem();
        System.out.println("The reaction value selected is " + reactant);
        if(reactant.equals("2")) {
            jTextField1.setBounds(10, 70, 110, 20);
            jTextField1.updateUI();
            jPanel2.add(jtestFieldReact2);
            jtestFieldReact2.setBounds(10, 110, 110, 20);
            jtestFieldReact2.setVisible(true);
            jtestFieldReact2.updateUI();

            jPanel2.add(reactantCombo1a);
            reactantCombo1a.setBounds(125, 70, 80, 20);
            reactantCombo1a.addItem("Deficent");
            reactantCombo1a.addItem("Excess");
            reactantCombo1a.setVisible(true);
            reactantCombo1a.updateUI();

            jPanel2.add(reactantCombo2);
            reactantCombo2.setBounds(125, 110, 80, 20);
            reactantCombo2.setVisible(true);;
            reactantCombo2.updateUI();

        } else if(reactant.equals("1")) {
            jTextField1.setBounds(10, 90, 110, 20);
            jTextField1.updateUI();
            jtestFieldReact2.setVisible(false);
            jPanel2.remove(jtestFieldReact2);
            // jtestFieldReact2.setVisible(false);
            jPanel2.updateUI();
            reactantCombo1a.setBounds(125, 90, 80, 20);
            reactantCombo1a.removeItem("Deficent");
            reactantCombo1a.removeItem("Excess");
            reactantCombo1a.updateUI();
//            jPanel2.remove(reactantCombo1);
//            jPanel2.updateUI();
            jPanel2.remove(reactantCombo2);
            jPanel2.updateUI();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        product = (String) jComboBox2.getSelectedItem();
        System.out.println("The value of the product selected is " + product);
        //jtextFiledPrduction
        if(product.equals("2")) {
            jTextField2.setBounds(220, 70, 110, 20);
            jTextField2.updateUI();
            jPanel2.add(jtextFiledPrduction);
            jtextFiledPrduction.setBounds(220, 110, 110, 20);
            jtextFiledPrduction.setVisible(true);
            jtextFiledPrduction.updateUI();

           jPanel2.add(productCombo1a);
           productCombo1a.setBounds(335, 70, 80, 20);
           productCombo1a.addItem("Deficent");
           productCombo1a.addItem("Excess");
           productCombo1a.setVisible(true);
           productCombo1a.updateUI();

            jPanel2.add(productCombo2);
            productCombo2.setBounds(335, 110, 80, 20);
            productCombo2.setVisible(true);
            productCombo2.updateUI();
          
        } else if(product.equals("1")) {
            jTextField2.setBounds(220, 90, 110, 20);
            jTextField2.updateUI();
            jtextFiledPrduction.setVisible(false);
            jPanel2.remove(jtextFiledPrduction);
            // jtestFieldReact2.setVisible(false);
            jPanel2.updateUI();
            //jPanel2.remove(productCombo1);
           productCombo1a.setBounds(335, 90, 80, 20);
           //productCombo1.setVisible(true);
           productCombo1a.removeItem("Deficent");
           productCombo1a.removeItem("Excess");
           productCombo1a.updateUI();
            jPanel2.updateUI();
            jPanel2.remove(productCombo2);
            jPanel2.updateUI();
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        rRM_ticked = jCheckBox1.isSelected();
        System.out.println(" Checked************* " + rRM_ticked );
        if(rRM_ticked)
        {
            jTextField3.setEditable(true);
            jTextField3.updateUI();
            jCheckBox1.updateUI();
        }
        else
        {
            jTextField3.setEditable(false);
            jTextField3.updateUI();
            jCheckBox1.updateUI();
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        if(rRM_ticked==true)
        {
            Cursor hourglassCursor = new Cursor(Cursor.N_RESIZE_CURSOR);
              setCursor(hourglassCursor);
        }
      

    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(normalCursor);

    }//GEN-LAST:event_jButton6MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        if(rRM_ticked==false)
        {
            Cursor hourglassCursor = new Cursor(Cursor.N_RESIZE_CURSOR);
              setCursor(hourglassCursor);
        }
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
          Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(normalCursor);
    }//GEN-LAST:event_jButton5MouseExited

    private void reactantCombo1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reactantCombo1aActionPerformed
        // TODO add your handling code here:
         reactionCombo_1Value = (String) reactantCombo1a.getSelectedItem();
        System.out.println("The selection from reaction 1 combo box is " + reactionCombo_1Value ) ;
    }//GEN-LAST:event_reactantCombo1aActionPerformed

    private void productCombo1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCombo1aActionPerformed
        // TODO add your handling code here:
         productCombo_1Value = (String) productCombo1a.getSelectedItem();
        System.out.println("The slection from product 1 combo box is " + productCombo_1Value );

    }//GEN-LAST:event_productCombo1aActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox productCombo1a;
    private javax.swing.JComboBox reactantCombo1a;
    // End of variables declaration//GEN-END:variables

}
