/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reaction.java
 *
 * Created on 01-Dec-2010, 23:10:59
 */



import javax.swing.JRootPane;

/**
 *
 * @author mhh
 */
public class Reactant2 extends javax.swing.JFrame {

    /** Creates new form Reaction */

    private String measuringUnitValue;

    public String rotoTypeSelected_1 = "ClassicalRotors";
    public String rotoTypeSelected_2 = "ClassicalRotors";
    public String rotationalConstantComboValue_1 = "cm-1";
    public String vibrationalFrequecnyComboValue_1 = "cm-1";
    public String rotationalConstantComboValue_2 = "cm-1";
    public String vibrationalFrequecnyComboValue_2 = "cm-1";
    public String reactantValue1;
    public String reactantValue2;

    public ExcelAdapter copyPast;
    public ExcelAdapter copyPast2;

    public Reactant2() {

        initComponents();
        //  setDefaultCloseOperation(2);
        vibrationFreqTable.setCellSelectionEnabled(true);
        copyPast = new ExcelAdapter(vibrationFreqTable);

       vibrationFreqTable2.setCellSelectionEnabled(true);
        copyPast2 = new ExcelAdapter(vibrationFreqTable2);
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         setResizable(false);
        setLocationRelativeTo(null);

       //  set


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        vibrationFreqTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        vibrationFreqTable = new javax.swing.JTable();
        jTextField11 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jTextField13 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 700));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18));
        jLabel1.setText("MESMER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(510, 0, 184, 40);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18));
        jLabel2.setText("Reactant 2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(870, 30, 310, 23);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Energy");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 20, 78, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Scaling Factor ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 220, 140, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("Rotational constants ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 58, 160, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Vibration frequencies ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 140, 160, 17);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 520, 10);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 100, 520, 10);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(0, 210, 520, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(280, 0, 60, 560);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(310, 10, 190, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField2);
        jTextField2.setBounds(310, 60, 190, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField4);
        jTextField4.setBounds(310, 220, 190, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cm-1" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(200, 60, 60, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cm-1" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(200, 140, 56, 20);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(0, 470, 520, 10);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("Symmetry");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 270, 110, 17);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField5);
        jTextField5.setBounds(310, 270, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setText("Molecular Weight (amu)  ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 320, 180, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel9.setText("Spin Multiplicity ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 370, 110, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setText("Density of States (DOS) ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 430, 170, 17);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(0, 260, 520, 10);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField6);
        jTextField6.setBounds(310, 320, 190, 30);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(0, 310, 520, 10);
        jPanel2.add(jSeparator8);
        jSeparator8.setBounds(0, 360, 520, 10);

        jLabel23.setText("kJ");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(120, 20, 100, 14);

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField15);
        jTextField15.setBounds(310, 370, 190, 30);
        jPanel2.add(jSeparator18);
        jSeparator18.setBounds(0, 410, 520, 10);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(290, 480, 220, 70);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel24.setText("Scientific Rational for Changes ");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(20, 480, 230, 17);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ClassicalRotors", "quantum mechanical" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox6);
        jComboBox6.setBounds(300, 440, 190, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setText("Rotor type ");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(360, 420, 80, 15);

        vibrationFreqTable2.setFont(new java.awt.Font("Tahoma", 0, 10));
        vibrationFreqTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Values"
            }
        ));
        vibrationFreqTable2.getTableHeader().setResizingAllowed(false);
        vibrationFreqTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(vibrationFreqTable2);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(310, 110, 190, 90);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(630, 60, 520, 560);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 630, 280, 23);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setText("Energy");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 20, 78, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel13.setText("Scaling Factor ");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 220, 140, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel14.setText("Rotational constants ");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 58, 160, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel15.setText("Vibration frequencies ");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 140, 160, 17);
        jPanel3.add(jSeparator9);
        jSeparator9.setBounds(0, 50, 520, 10);
        jPanel3.add(jSeparator10);
        jSeparator10.setBounds(0, 100, 520, 10);
        jPanel3.add(jSeparator11);
        jSeparator11.setBounds(0, 210, 520, 10);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator12);
        jSeparator12.setBounds(280, 0, 60, 560);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField8);
        jTextField8.setBounds(310, 10, 190, 30);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField9);
        jTextField9.setBounds(310, 60, 190, 30);

        vibrationFreqTable.setFont(new java.awt.Font("Tahoma", 0, 10));
        vibrationFreqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Values"
            }
        ));
        vibrationFreqTable.getTableHeader().setResizingAllowed(false);
        vibrationFreqTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(vibrationFreqTable);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(310, 110, 190, 90);

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField11);
        jTextField11.setBounds(310, 220, 190, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cm-1" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(200, 60, 60, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cm-1" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox5);
        jComboBox5.setBounds(200, 140, 56, 20);
        jPanel3.add(jSeparator13);
        jSeparator13.setBounds(0, 470, 520, 10);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel16.setText("Symmetry");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 270, 110, 17);

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField12);
        jTextField12.setBounds(310, 270, 190, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel17.setText("Molecular Weight (amu)  ");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 320, 180, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel18.setText("Spin Multiplicity ");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(10, 370, 110, 17);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel19.setText("Scientific Rational for Changes ");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 480, 230, 17);
        jPanel3.add(jSeparator14);
        jSeparator14.setBounds(0, 260, 520, 10);

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField13);
        jTextField13.setBounds(310, 320, 190, 30);
        jPanel3.add(jSeparator15);
        jSeparator15.setBounds(0, 310, 520, 10);
        jPanel3.add(jSeparator16);
        jSeparator16.setBounds(0, 360, 520, 10);

        jLabel22.setText("kJ");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(120, 20, 100, 14);

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField16);
        jTextField16.setBounds(310, 370, 190, 30);
        jPanel3.add(jSeparator17);
        jSeparator17.setBounds(0, 410, 520, 10);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(290, 480, 220, 70);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel20.setText("Density of States (DOS) ");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 430, 170, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ClassicalRotors", "quantum mechanical" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(300, 440, 190, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("Rotor type ");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(360, 420, 80, 15);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(40, 60, 520, 560);

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 18));
        jLabel21.setText("Reactant 1");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(260, 30, 330, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      //  setVisit
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        rotoTypeSelected_1 = (String) jComboBox1.getSelectedItem();

}//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
     rotoTypeSelected_2  =  (String) jComboBox6.getSelectedItem();
}//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:

        rotationalConstantComboValue_1 = (String) jComboBox4.getSelectedItem();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        vibrationalFrequecnyComboValue_1  = (String) jComboBox5.getSelectedItem();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
       rotationalConstantComboValue_2  = (String) jComboBox2.getSelectedItem();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
       vibrationalFrequecnyComboValue_2  = (String) jComboBox3.getSelectedItem();
    }//GEN-LAST:event_jComboBox3ActionPerformed

     public void initialisationValueDisplay(String reactantValue1, String reactantValue2)
     {
         this.reactantValue1 = reactantValue1;
         this.reactantValue2 = reactantValue2;
         jLabel21.setText(reactantValue1);
         jLabel21.updateUI();
         System.out.println("The value of reactant 1 is " + reactantValue1);
         jLabel2.setText(reactantValue2);
         jLabel2.updateUI();
         System.out.println("The value of reactant 2 is " + reactantValue2);
         measuringUnitValue = MESMER_v3.measuringUnitValue;
         jLabel22.setText(measuringUnitValue);
         jLabel22.updateUI();
         jLabel23.setText(measuringUnitValue);
         jLabel23.updateUI();

    }

     public String getReactantValue1()
     {
            return reactantValue1;
     }

     public String getReactantValue2()
     {
         return reactantValue2;
     }

     public String getEnergy_1()
     {
         return jTextField8.getText();
     }

     public String getRotationalConstant_1()
     {
         return   jTextField9.getText();
     }

     public String getRotationalConstantComboSetlected_1()
    {
     return rotationalConstantComboValue_1;
    }


     public String getVibrationalFrequency_1()
     {
        String allValues, eachValue;
        allValues="";
        eachValue ="";
        for(int i = 0; i < vibrationFreqTable.getRowCount(); i++){
        System.out.println( vibrationFreqTable.getValueAt(i, 0));
        eachValue =(String) vibrationFreqTable.getValueAt(i, 0);
           if(eachValue==null  || eachValue.equals(""))
           {
               System.out.println("Found break");
               break;
           }
           else
              allValues+= eachValue + " ";
        }
        System.out.println("All values are " + allValues);

        return  allValues;

     }


 public String getVibrationalFrequencyComboSelected_1()
 {
     return vibrationalFrequecnyComboValue_1;
 }

     public String getScalingFactor_1()
     {
         return jTextField11.getText();
     }

     public String getSymmetry_1()
     {
         return jTextField12.getText();
     }

     public String getMolecularWeight_1()
     {
         return jTextField13.getText();
     }

     public String getSpinMultiplicity_1()
     {
         return jTextField16.getText();
     }

     public String getDensityofState_1()
     {
         return rotoTypeSelected_1;
     }

     public String getScientificRational_1()
     {
         return jTextArea1.getText();
     }

     public String getEnergy_2()
     {
         return  jTextField1.getText();
     }

     public String getRotationalConstant_2()
     {
         return jTextField2.getText();
     }

     public String getRotationalConstantComboSetlected_2()
    {
         return rotationalConstantComboValue_2;
    }


     public String getVibrationalFrequency_2()
     {
        String allValues, eachValue;
        allValues="";
        eachValue ="";
        for(int i = 0; i < vibrationFreqTable2.getRowCount(); i++){
            System.out.println( vibrationFreqTable2.getValueAt(i, 0));
            eachValue =(String) vibrationFreqTable2.getValueAt(i, 0);
            if(eachValue==null  || eachValue.equals(""))
            {
               System.out.println("Found break");
               break;
           }
           else
              allValues+= eachValue + " ";
        }
        System.out.println("All values are " + allValues);
        return  allValues;
     }


      public String getVibrationalFrequencyComboSelected_2()
      {
            return vibrationalFrequecnyComboValue_2;
       }

     public String getScalingFactor_2()
     {
         return jTextField4.getText();
     }

     public String getSymmetry_2()
     {
         return jTextField5.getText();
     }

     public String getMolecularWeight_2()
     {
         return jTextField6.getText();
     }

     public String getSpinMultiplicity_2()
     {
         return jTextField15.getText();
     }

     public String getDensityofState_2()
     {
         return rotoTypeSelected_2;
     }

     public String getScientificRational_2()
     {
         return jTextArea2.getText();
     }




    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reactant2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable vibrationFreqTable;
    private javax.swing.JTable vibrationFreqTable2;
    // End of variables declaration//GEN-END:variables

}
