/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReactionPan2.java
 *
 * Created on 15-Dec-2010, 12:18:51
 */



import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author mhh
 */
public class ReactionPan2b extends javax.swing.JPanel {


     /** Creates new form MainGUI */
    String method = "RRKM";
    String reactant ="1";
    String product = "1";
    JTextField jtestFieldReact2 = new JTextField();
    JTextField jtextFiledPrduction = new JTextField();

    /** Creates new form ReactionPan2 */
    public ReactionPan2b() {
        initComponents();

    }

    public ReactionPan2b(int reactionNumber)
    {
        initComponents();
        //setDefaultCloseOperation ( JFrame.EXIT_ON_CLOSE );
        jLabel6.setText("Reaction " + reactionNumber);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(730, 170));
        setPreferredSize(new java.awt.Dimension(730, 170));
        setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(730, 170));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 170));
        jPanel2.setLayout(null);

        jButton3.setText("Fill Reactant");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(20, 120, 110, 23);

        jButton4.setText("Fill Product");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(180, 120, 146, 23);

        jButton5.setText("Fill Transition State");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(370, 120, 166, 23);

        jButton6.setText("Fill Method");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(580, 120, 138, 23);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(20, 80, 110, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(180, 80, 150, 20);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(370, 80, 183, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(80, 30, 40, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(270, 30, 50, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RRKM", "ILT" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(590, 80, 102, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Reactant");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 30, 66, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Product");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 30, 92, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Transition State");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(400, 30, 126, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Method");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(590, 30, 126, 20);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(560, 30, 50, 140);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(160, 30, 50, 140);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(350, 30, 50, 140);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(0, 60, 730, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Reaction 1");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, -3, 730, 30);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 730, 170);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(reactant.equals("1"))
            new Reactant1().setVisible(true);
        else
            new Reactant2().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(product.equals("1"))
            new Product1().setVisible(true);
        else
            new Product2().setVisible(true);
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new TransitionState().setVisible(true);
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(method.equals("RRKM")) {
            // new ILTMethod().setVisible(true);
            new RRKM_Method().setVisible(true);
        } else if(method.equals("ILT")) {
            new ILTMethod().setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        reactant = (String) jComboBox1.getSelectedItem();
        if(reactant.equals("2")) {
            jTextField1.setBounds(20, 80, 50, 20);
            jTextField1.updateUI();
            jPanel2.add(jtestFieldReact2);
            jtestFieldReact2.setBounds(90, 80, 50, 20);
            jtestFieldReact2.setVisible(true);
            jtestFieldReact2.updateUI();
        } else if(reactant.equals("1")) {
            jTextField1.setBounds(20, 80, 110, 20);
            jTextField1.updateUI();
            jtestFieldReact2.setVisible(false);
            jPanel2.remove(jtestFieldReact2);
            // jtestFieldReact2.setVisible(false);
            jPanel2.updateUI();


        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        product = (String) jComboBox2.getSelectedItem();
        //jtextFiledPrduction
        if(product.equals("2")) {
            jTextField2.setBounds(170, 80, 60, 20);
            jTextField2.updateUI();
            jPanel2.add(jtextFiledPrduction);
            jtextFiledPrduction.setBounds(250,80,70,20);
            jtextFiledPrduction.setVisible(true);
            jtextFiledPrduction.updateUI();
        } else if(product.equals("1")) {
            jTextField2.setBounds(180, 80, 150, 20);
            jTextField2.updateUI();
            jtextFiledPrduction.setVisible(false);
            jPanel2.remove(jtextFiledPrduction);
            // jtestFieldReact2.setVisible(false);
            jPanel2.updateUI();


        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        method = (String) jComboBox3.getSelectedItem();
    }//GEN-LAST:event_jComboBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
