/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reaction.java
 *
 * Created on 01-Dec-2010, 23:10:59
 */



import javax.swing.JRootPane;

/**
 *
 * @author mhh
 */
public class TransitionState extends javax.swing.JFrame {

    public String rotorTypeSelected = "ClassicalRotors";
    public String rotationalConstantComboValue = "cm-1";
    public String vibrationalFrequecnyComboValue = "cm-1";
    public String transitionStateValue;
    public String measuringUnitValue;
    public ExcelAdapter copyPast;

    /** Creates new form Reaction */
    public TransitionState() {

        initComponents();
        //  setDefaultCloseOperation(2);
         vibrationFreqTable.setCellSelectionEnabled(true);
        copyPast = new ExcelAdapter(vibrationFreqTable);
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         setLocationRelativeTo(null);
         setResizable(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        vibrationFreqTable = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(593, 340));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18));
        jLabel1.setText("MESMER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 0, 184, 40);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18));
        jLabel2.setText("Transition State");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 30, 360, 23);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Energy");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 20, 78, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Scaling Factor ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 220, 120, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("Rotational constants ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 58, 160, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Vibration frequencies ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 140, 160, 17);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 520, 10);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 100, 520, 10);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(10, 210, 520, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(280, 0, 60, 620);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(310, 10, 190, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField2);
        jTextField2.setBounds(310, 60, 190, 30);

        vibrationFreqTable.setFont(new java.awt.Font("Tahoma", 0, 10));
        vibrationFreqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Values"
            }
        ));
        vibrationFreqTable.getTableHeader().setResizingAllowed(false);
        vibrationFreqTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(vibrationFreqTable);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(310, 110, 190, 90);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField4);
        jTextField4.setBounds(310, 220, 190, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cm-1" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(200, 60, 60, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cm-1" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(200, 140, 56, 20);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(0, 520, 520, 10);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("Symmetry");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 270, 110, 17);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField5);
        jTextField5.setBounds(310, 270, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setText("Molecular Weight (amu)  ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 320, 180, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel9.setText("Spin Multiplicity ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 370, 110, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setText("Scientific Rational for Changes ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 540, 210, 17);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(0, 260, 520, 10);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField6);
        jTextField6.setBounds(310, 320, 190, 30);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextField7);
        jTextField7.setBounds(300, 480, 190, 30);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(0, 310, 520, 10);
        jPanel2.add(jSeparator8);
        jSeparator8.setBounds(0, 360, 520, 10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("Rotor type ");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(360, 420, 80, 15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ClassicalRotors", "quantum mechanical" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(300, 440, 190, 20);
        jPanel2.add(jSeparator9);
        jSeparator9.setBounds(0, 410, 520, 10);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8);
        jTextField8.setBounds(310, 370, 190, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setText("Density of States (DOS) ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 430, 170, 17);
        jPanel2.add(jSeparator10);
        jSeparator10.setBounds(0, 470, 520, 10);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel13.setText("Imaginative Frequency     ");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 480, 170, 17);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(300, 530, 190, 60);

        jLabel14.setText("kJ");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(120, 20, 100, 14);

        jScrollPane2.setViewportView(jPanel2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 60, 530, 520);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 610, 170, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initialisationValueDisplay(String transitionStateValue)
    {
     this.transitionStateValue = transitionStateValue;
     jLabel2.setText(transitionStateValue);
     jLabel2.updateUI();
     System.out.println("The value of reactant is " + transitionStateValue);
     measuringUnitValue = MESMER_v3.measuringUnitValue;
     jLabel14.setText(measuringUnitValue);
     jLabel14.updateUI();
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      //  setVisit
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


   public String getTransitionStateValue()
 {
     return transitionStateValue;
 }

 public String getGetEnergy()
 {
    return jTextField1.getText();
 }

 public String getRotationalConstants()
 {
    return jTextField2.getText();
 }

 public String getRotationalConstantComboSetlected()
 {
     return rotationalConstantComboValue;
 }

 public String getVibrationalFrequecy()
 {
    String allValues, eachValue;
    allValues="";
    eachValue ="";
    for(int i = 0; i < vibrationFreqTable.getRowCount(); i++){
        System.out.println( vibrationFreqTable.getValueAt(i, 0));
        eachValue =(String) vibrationFreqTable.getValueAt(i, 0);
           if(eachValue==null)
           {
               System.out.println("Found break");
               break;
           }
           else
              allValues+= eachValue + " ";
      }
     System.out.println("All values are " + allValues);

     return  allValues;
 }

  public String getVibrationalFrequencyComboSelected()
 {
     return vibrationalFrequecnyComboValue;
 }

 public String getScalingFactor()
 {
    return jTextField4.getText();
 }

 public String getSymmerty()
 {
    return jTextField5.getText();
 }

 public String getMolecularWeight()
 {
    return jTextField6.getText();
 }

 public String getSpinMulticity()
 {
    return jTextField8.getText();
 }

 public String getDensityOfState()
 {
    return rotorTypeSelected;
 }

public String getImaginitiveFrequency()
{
    return jTextField7.getText();
}

 public String getScienfifiRational()
 {
    return jTextArea1.getText();
 }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         rotorTypeSelected = (String) jComboBox1.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        rotationalConstantComboValue = (String) jComboBox2.getSelectedItem();

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
      vibrationalFrequecnyComboValue  = (String) jComboBox3.getSelectedItem();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransitionState().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable vibrationFreqTable;
    // End of variables declaration//GEN-END:variables

}
