
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewAllRecordFrame.java
 *
 * Created on 03-Feb-2011, 22:59:51
 */

/**
 *
 * @author mhh
 */
public class ViewAllRecordFrame extends javax.swing.JFrame {

    Component[] allComponents;
    String unit;
    String gasBufferValue;
    int height =  110;
    /** Creates new form ViewAllRecordFrame */
    public ViewAllRecordFrame() {
        initComponents();
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         setLocationRelativeTo(null);
         setResizable(false);
    }

     public ViewAllRecordFrame(Component[] allComponents, String unit, String gasBufferValue) {
        initComponents();
        this.unit = unit;
        this.allComponents = allComponents;
        this.gasBufferValue = gasBufferValue;
    
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         setLocationRelativeTo(null);
         setResizable(false);
         displayAllReactions();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 600));
        jPanel1.setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 700));
        getContentPane().setLayout(null);

        jPanel2.setMinimumSize(new java.awt.Dimension(600, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 800));
        jPanel2.setLayout(null);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(290, 630, 230, 23);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18));
        jLabel1.setText("MESMER");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(320, 0, 184, 40);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 820, 490);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Summary Of All Records ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 34, 260, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("NAME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 80, 60, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("Energy");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(180, 70, 60, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("kJ/mol");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(180, 90, 80, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setText("cm-1");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(360, 100, 80, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Vibrational frequency ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(540, 70, 210, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("cm-1");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(590, 90, 80, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("Rotational");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(340, 60, 80, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("constants");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(340, 80, 80, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 840, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    public void displayAllReactions()
    {
        ReactionPan2 reactantValues;
        jLabel7.setText(unit);

        for(int i =0; i< allComponents.length; i++)
        {
            reactantValues = (ReactionPan2) allComponents[i];

            if(reactantValues.getNo_ReactantComboSelected().equals("1") )
            {
                  height += 110;
                  jPanel3.add(new  ViewAllRecordJpanel(reactantValues.getReactant_1TextField(), reactantValues.reactant1Input.getGetEnergy(),
                 reactantValues.reactant1Input.getRotationalConstants(),  reactantValues.reactant1Input.getVibrationalFrequecy()));
                 jPanel3.setPreferredSize(new Dimension(740,height));
                 jScrollPane1.setViewportView(jPanel3);
                 jScrollPane1.updateUI();

                 
                   System.out.println("############################# Reactionm1 ###############################################");
                   System.out.println("Reaction ");
                   System.out.println( "************** " + i + "******************");
                   System.out.println("******Reactant value is ********" + reactantValues.getReactant_1TextField());
                   System.out.println( "******Energy ***** " +  i + " "+  reactantValues.reactant1Input.getGetEnergy());
                   System.out.println("******Rotational Constants " + reactantValues.reactant1Input.getRotationalConstants());
                   System.out.println( "****** Vibrational Frequency " +  reactantValues.reactant1Input.getVibrationalFrequecy());
                  
            }
            
           if(reactantValues.getNo_ReactantComboSelected().equals("2") )
            {

               height +=110 ;
              jPanel3.add(new  ViewAllRecordJpanel(reactantValues.getReactant_1TextField(),
              reactantValues.reactant2Input.getEnergy_1(), reactantValues.reactant2Input.getRotationalConstant_1(),
              reactantValues.reactant2Input.getVibrationalFrequency_1()));
              jPanel3.setPreferredSize(new Dimension(740,height));
              jScrollPane1.setViewportView(jPanel3);
              jScrollPane1.updateUI();

              height += 110;
              jPanel3.add(new  ViewAllRecordJpanel(reactantValues.getReactant_2TextField(),
              reactantValues.reactant2Input.getEnergy_2(), reactantValues.reactant2Input.getRotationalConstant_2(),
              reactantValues.reactant2Input.getVibrationalFrequency_2()));
              jPanel3.setPreferredSize(new Dimension(740,height));
              jScrollPane1.setViewportView(jPanel3);
              jScrollPane1.updateUI();


                System.out.println("############################## Reaction 2 ##############################################");
                System.out.println("Reaction2 ");

                System.out.println("****** Reactant 1 " + reactantValues.getReactant_1TextField());
                System.out.println("****** Combo Selected 1 " + reactantValues.getReactantCombo1());

                System.out.println("****** Energy" + reactantValues.reactant2Input.getEnergy_1() );
                System.out.println("****** RotaitonalConstant " + reactantValues.reactant2Input.getRotationalConstant_1() );
                System.out.println("****** Vib Frequency " + reactantValues.reactant2Input.getVibrationalFrequency_1() );


                 System.out.println("****** Reactant 2 " + reactantValues.getReactant_2TextField());
                System.out.println("****** Combo Selected 1 " + reactantValues.getReactantCombo2());
                System.out.println("****** Energy " +  reactantValues.reactant2Input.getEnergy_2() );
                System.out.println("****** RotaitonalConstant " + reactantValues.reactant2Input.getRotationalConstant_2() );
                System.out.println("******Vib Frequency " + reactantValues.reactant2Input.getVibrationalFrequency_2() );


            }
           if(reactantValues.getNo_ProductComboSelected().equals("1"))
           {

               height += 110;
              jPanel3.add(new  ViewAllRecordJpanel(reactantValues.getProduct_1TextField(),
                reactantValues.product1Input.getGetEnergy(), reactantValues.product1Input.getRotationalConstants(),
               reactantValues.product1Input.getVibrationalFrequecy()));
              jPanel3.setPreferredSize(new Dimension(740,height));
              jScrollPane1.setViewportView(jPanel3);
              jScrollPane1.updateUI();



              System.out.println("############################Product 1 ################################################");
            System.out.println("Product ");

            System.out.println( "************** " + i + "******************");
            System.out.println("******Reactant value is ********" + reactantValues.getProduct_1TextField());
            System.out.println( "******Energy ***** " +  i + " "+  reactantValues.product1Input.getGetEnergy());
            System.out.println("******Rotational Constants " + reactantValues.product1Input.getRotationalConstants());
            System.out.println( "****** Vibrational Frequency " +  reactantValues.product1Input.getVibrationalFrequecy());

	   }
          if(reactantValues.getNo_ProductComboSelected().equals("2"))
          {

               height += 110;
              jPanel3.add(new  ViewAllRecordJpanel( reactantValues.getProduct_1TextField(),
                reactantValues.product2Input.getEnergy_1(), reactantValues.product2Input.getRotationalConstant_1(),
               reactantValues.product2Input.getVibrationalFrequency_1()));
              jPanel3.setPreferredSize(new Dimension(740,height));
              jScrollPane1.setViewportView(jPanel3);
              jScrollPane1.updateUI();

              height += 110;
              jPanel3.add(new  ViewAllRecordJpanel( reactantValues.getProduct_2TextField(),
                reactantValues.product2Input.getEnergy_2(), reactantValues.product2Input.getRotationalConstant_2(),
               reactantValues.product2Input.getVibrationalFrequency_2()));
              jPanel3.setPreferredSize(new Dimension(740,height));
              jScrollPane1.setViewportView(jPanel3);
              jScrollPane1.updateUI();


             System.out.println("############################Product 2 ################################################");
            System.out.println("Product 2 ");

            System.out.println("****** Product 1 " + reactantValues.getProduct_1TextField());
            System.out.println(" ***** Combo 1 selected " +  reactantValues.getProductCombo1());

            System.out.println("****** Energy" + reactantValues.product2Input.getEnergy_1() );
            System.out.println("****** RotaitonalConstant " + reactantValues.product2Input.getRotationalConstant_1() );
            System.out.println("****** Vib Frequency " + reactantValues.product2Input.getVibrationalFrequency_1() );

            System.out.println("****** Product 2 " + reactantValues.getProduct_2TextField());
            System.out.println(" ***** Combo 2 selected " +  reactantValues.getProductCombo2());
            System.out.println("****** Energy " +  reactantValues.product2Input.getEnergy_2() );
            System.out.println("****** RotaitonalConstant " + reactantValues.product2Input.getRotationalConstant_2() );
            System.out.println("******Vib Frequency " + reactantValues.product2Input.getVibrationalFrequency_2() );


	  }
            //accommodate transition
                 if(reactantValues.get_RRKM())
                 {
                     height += 110;
                    jPanel3.add(new  ViewAllRecordJpanel(reactantValues.get_TransitionStateValue(),reactantValues.transitionStateInput.getGetEnergy(),
                    reactantValues.transitionStateInput.getRotationalConstants(),  reactantValues.transitionStateInput.getVibrationalFrequecy()));
                    jPanel3.setPreferredSize(new Dimension(740,height));
                    jScrollPane1.setViewportView(jPanel3);
                    jScrollPane1.updateUI();

                     System.out.println("Transition  ");
                     System.out.println("****** " + reactantValues.get_TransitionStateValue() );
                     System.out.println("****** " + reactantValues.transitionStateInput.getGetEnergy() );
                     System.out.println("****** " + reactantValues.transitionStateInput.getRotationalConstants());
                     System.out.println("****** " + reactantValues.transitionStateInput.getVibrationalFrequecy() );


                 }

        }
        //as the flow is centred this is to ensure the lable is show on the left
        String space = "                                                                                      ";
        gasBufferValue += space + space + "                ";
        JLabel basBufferlable = new JLabel(gasBufferValue);
        basBufferlable.setFont(new java.awt.Font("Tahoma", 1, 14));
        height += 110;
        jPanel3.add(basBufferlable);
        jPanel3.updateUI();

    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
